// 'use server';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '../style/global.css'
import Nav from '@/components/navbar/index'
import UserInfo from '@/components/user/userinfo'
import { headers } from 'next/headers'
import NextAuthSessionProvider from "@/provider/SessionProvider";
import {getServerSession} from 'next-auth'

export default async function RootLayout({children,}: {children: React.ReactNode}) {

  const headersList = headers()
  const userAcc = headersList.get('user-account')
  let userAccountJson

  if(userAcc){
    userAccountJson=JSON.parse(userAcc)
  }

  const session = await getServerSession();

  let user = (
    <UserInfo user={userAccountJson}></UserInfo>
  )
  return (
    <html lang="en">
      <body style={{backgroundColor:'gray'}}>

        <NextAuthSessionProvider>

          <Nav user={user}></Nav>

          <div style={{height:'70px'}}></div>
          <div>
            {!session &&
            <span>Login</span>
            }

            {!!session &&
            <span>Logout</span>
            }
          </div>

          {children}

        </NextAuthSessionProvider>
      </body>
    </html>
  )
}